name: Web API Deploy Pipeline
on:
  push:
    paths:
      - ".github/workflows/**"
      - "main.go"

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: my-app-cluster
  ECS_SERVICE: deploy_pipeline_service_example
  ECS_REPOSITORY: ecs_deploy_pipeline
  ECS_TASK_DEFINITION_API: .aws/task-def-api.json

# OpenID connectに必要な権限
permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Run tests
        run: go test .

      - name: Build an image
        run: docker image build -t temp_api_image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          # For OpenID connect
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECS_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECS_REPOSITORY:${{ github.sha }}
